# Generated by Django 5.1.3 on 2024-12-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_chat_massage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Massage',
            new_name='Message',
        ),
    ]
